import uuid
from pathlib import Path
from typing import Annotated

from fastapi import Depends

from app.config import Settings, get_settings


class LocalStorage:
    """Stores files on the local filesystem under a root directory.

    Keys are relative paths generated by the service (see `build_key`), never user input.
    """

    def __init__(self, root: Path) -> None:
        self.root = root.resolve()

    def path(self, key: str) -> Path:
        path = (self.root / key).resolve()
        if not path.is_relative_to(self.root):
            raise ValueError(f"Invalid storage key: {key!r}")
        return path

    def save(self, key: str, data: bytes) -> None:
        path = self.path(key)
        path.parent.mkdir(parents=True, exist_ok=True)
        # Write to a temporary file first so readers never see a partially written image.
        tmp_path = path.with_name(f".{path.name}.{uuid.uuid4().hex}.tmp")
        try:
            tmp_path.write_bytes(data)
            tmp_path.replace(path)
        finally:
            tmp_path.unlink(missing_ok=True)

    def read(self, key: str) -> bytes:
        return self.path(key).read_bytes()

    def delete(self, key: str) -> None:
        self.path(key).unlink(missing_ok=True)


def build_key(owner_id: uuid.UUID, extension: str) -> str:
    return f"{owner_id}/{uuid.uuid4().hex}.{extension}"


def get_storage(settings: Annotated[Settings, Depends(get_settings)]) -> LocalStorage:
    return LocalStorage(settings.storage_dir)
